### PR TITLE
added a save button

### PR DESCRIPTION
**Pull request by HassanShanJava**
-Added a save button bellow the clear board button
-Made updates in style.css, index.html, and script.js to add the save image feature 

after:

save button
save feature

### CODE REVIEW

**Comment by HassanShanJava** [comment]
-Hi I realize of few of my mistakes with the button sizing so I fixed it and push it again. do let me know if you want anything changed.

changes:
image

it can still function well and properly save the image drawn.

**Comment by DhanushNehru** [comment]
There are some merge conflicts @HassanShanJava 

And also if i change the background color to green & save it the image background color doesn't seem to be green

**Comment by HassanShanJava** [comment]
Its not to supposed to save with background because the file type is png. It only saves what you draw, basically like a signature save

**Comment by myckgoncalves** [comment]
I agree with @DhanushNehru , we should save the image with the chosen background color.

Imagine a situation where we make all the color choices to make a drawing based on the background color, some colors will no longer make sense without that background color.

@HassanShanJava I can't see the .PNG file type being an obstacle to applying the chosen background color :thinking:

I'll code something along these lines and I'll come back with a solution for us to discuss.

**Comment by HassanShanJava** [comment]
All right, I have an idea on how to save with background color, I'll send it soom

**Comment by HassanShanJava** [comment]
Please check again, I added the save with background color feature:

Change:
background save

background saved image

**Comment by DhanushNehru** [comment]
Please resolve the merge conflicts @HassanShanJava

**Comment by HassanShanJava** [comment]
Could you explain??, What are the conflicts

**Comment by HassanShanJava** [comment]
nevermind, i see someone else did it

**Pull request closed without merging**
