### PR TITLE
Feature/google signin

### PR DESCRIPTION
**Pull request by JeevaRamanathan**
Fix for #49 
While merging please do create a project in https://console.cloud.google.com/ and under Apis and Services i. create a OAuth 2.0 client id for web application and replace the client id in index.html (line 59). ii) Also add the Authorized JavaScript origins in OAuth 2.0 of the web app end point. If anything goes wrong kindly let me know!

### CODE REVIEW

**Comment by DhanushNehru** [comment]
Hi @JeevaRamanathan the client id etc, can that be as environment variables.
And also the steps to be followed can you add images as well

**Comment by JeevaRamanathan** [comment]
Hi @DhanushNehru ,
1. As html is a markup language it does not handle env variables, so now I have approached that in a different way using config,json file, so the client_id can be directly updated in config file.

2.Steps to be followed to enable and get the data-client_id

- Create a Google Cloud Project:
Go to the Google Cloud Console (https://console.cloud.google.com/) and create a new project.
image

- Configure OAuth Consent Screen:
In the Google Cloud Console, navigate to created project's "APIs & Services" > "OAuth consent screen."
Configure the OAuth consent screen with the all required details like app name, user support email, etc.

- Create OAuth 2.0 Client ID:
Navigate to "APIs & Services" > "Credentials."
Click on the "Create Credentials" button and select "OAuth client ID."
Choose the application type as  Web application.
Add authorized JavaScript origins for the application. (i.e https://board-dhanushnehru.netlify.app/) 
Once created, the "Client ID" will be generated. Replace that client id in the config.json file 

image

Please follow the above steps and if you are facing any issues please let me know

**Review by DhanushNehru — APPROVED** [review]

**Review by DhanushNehru — APPROVED** [review]

**Comment by DhanushNehru** [comment]
Thanks for your contribution @JeevaRamanathan , if you can update the readme.md / contribution.md guidelines

Or create an issue to update those, it would be very helpful for new users

**Comment by JeevaRamanathan** [comment]
Hi @DhanushNehru, Sure! I have raised a PR updating readme.md. #61

**Pull request merged**
